### PR TITLE
make v2 demo/html endpoint return pretty html output

### PR DESCRIPTION
**Pull request by JakeChampion**
Resolves https://github.com/Financial-Times/origami-build-service/issues/450

### CODE REVIEW

**Comment by notlee** [comment]
I don't think this is handling all the cases we want it to @JakeChampion?

The forms demo html isn't looking great on the dev instance at least
https://origami-build-service-dev.herokuapp.com/v2/demos/o-forms@8.4.1/checkboxes/html?brand=master
```
<div class="o-forms-field
		
		
		 o-forms-field--optional
		" role="group" aria-labelledby="checkbox-group-title" aria-describedby="checkbox-group-info">

  <span class="o-forms-title">
			<span class="o-forms-title__main" id="checkbox-group-title">Stacked checkboxes</span>
  <span class="o-forms-title__prompt" id="checkbox-group-info">Optional prompt/description text</span>
  </span>

  <span class="o-forms-input o-forms-input--checkbox">



				<label>
					<input type="checkbox" name="default" value="Stacked 1" checked>

						<span class="o-forms-input__label
									
									">
									Stacked 1
						</span>

  </label>
  <label>
    <input type="checkbox" name="default" value="Stacked 2">

    <span class="o-forms-input__label
									
									">
									Stacked 2
						</span>

  </label>
  <label>
    <input type="checkbox" name="default" value="Stacked 3" checked>

    <span class="o-forms-input__label
									
									">
									Stacked 3
						</span>

  </label>





  </span>

</div>
```

https://origami-build-service-eu.herokuapp.com/v2/demos/o-forms@8.4.1/checkboxes/html?brand=master

```
<div class="o-forms-field
		
		
		 o-forms-field--optional
		" role="group" aria-labelledby="checkbox-group-title" aria-describedby="checkbox-group-info">

		<span class="o-forms-title">
			<span class="o-forms-title__main" id="checkbox-group-title">Stacked checkboxes</span>
				<span class="o-forms-title__prompt" id="checkbox-group-info">Optional prompt/description text</span>
		</span>

		<span class="o-forms-input o-forms-input--checkbox">

			

				<label>
					<input type="checkbox" name="default" value="Stacked 1" checked>

						<span class="o-forms-input__label
									
									">
									Stacked 1
						</span>

				</label>
				<label>
					<input type="checkbox" name="default" value="Stacked 2">

						<span class="o-forms-input__label
									
									">
									Stacked 2
						</span>

				</label>
				<label>
					<input type="checkbox" name="default" value="Stacked 3" checked>

						<span class="o-forms-input__label
									
									">
									Stacked 3
						</span>

				</label>

			

			

		</span>

	</div>
```

**Comment by JakeChampion** [comment]
> I don't think this is handling all the cases we want it to @JakeChampion?
> 
> The forms demo html isn't looking great on the dev instance at least
> [origami-build-service-dev.herokuapp.com/v2/demos/o-forms@8.4.1/checkboxes/html?brand=master](https://origami-build-service-dev.herokuapp.com/v2/demos/o-forms@8.4.1/checkboxes/html?brand=master)

I believe that's because the dev instance is not using the code from this pull-request, it is using the code from the newer pull-request I've made to change modules query parameter to components -- https://github.com/Financial-Times/origami-build-service/pull/468

**Comment by notlee** [comment]
oh woops my bad 🙈

**Comment by notlee** [comment]
I noticed a difference in the output and assumed it was reflecting this pull request

**Pull request merged**
